# Pré-Processamento

In [3]:
# Importando pacotes

import numpy as np
import pandas as pd
import pickle

## Carregamento e verificando Inicial do dataset

In [5]:
# Importando dados

df = pd.read_csv("dados/dataset.csv")

In [6]:
df.head(10)

,X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,...,X170,X171,X172,X173,X174,X175,X176,X177,X178,LABEL_TARGET
0,135,190,229,223,192,125,55,-9,-33,-38,...,-17,-15,-31,-77,-103,-127,-116,-83,-51,False
1,386,382,356,331,320,315,307,272,244,232,...,164,150,146,152,157,156,154,143,129,True
2,-32,-39,-47,-37,-32,-36,-57,-73,-85,-94,...,57,64,48,19,-12,-30,-35,-35,-36,False
3,-105,-101,-96,-92,-89,-95,-102,-100,-87,-79,...,-82,-81,-80,-77,-85,-77,-72,-69,-65,False
4,-9,-65,-98,-102,-78,-48,-16,0,-21,-59,...,4,2,-12,-32,-41,-65,-83,-89,-73,False
5,55,28,18,16,16,19,25,40,52,66,...,-12,-31,-42,-54,-60,-64,-60,-56,-55,False
6,-55,-9,52,111,135,129,103,72,37,0,...,-125,-99,-79,-62,-41,-26,11,67,128,False
7,1,-2,-8,-11,-12,-17,-15,-16,-18,-17,...,-79,-91,-97,-88,-76,-72,-66,-57,-39,False
8,-278,-246,-215,-191,-177,-167,-157,-139,-118,-92,...,-400,-379,-336,-281,-226,-174,-125,-79,-40,True
9,8,15,13,3,-6,-8,-5,4,25,41,...,49,31,11,-5,-17,-19,-15,-15,-11,False

In [7]:
print("Distribuição da Variavel Alvo: ", df['LABEL_TARGET'].value_counts())
print("\nQuantidade de registros nulos: ", df.isnull().sum().sum())
print()
df.info()

Distribuição da Variavel Alvo:  LABEL_TARGET
False    9200
True     2300
Name: count, dtype: int64

Quantidade de registros nulos:  0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11500 entries, 0 to 11499
Columns: 179 entries, X1 to LABEL_TARGET
dtypes: bool(1), int64(178)
memory usage: 15.6 MB

In [8]:
df.describe()

,X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,...,X169,X170,X171,X172,X173,X174,X175,X176,X177,X178
count,11500.000000,11500.000000,11500.000000,11500.000000,11500.000000,11500.000000,11500.000000,11500.00000,11500.00000,11500.000000,...,11500.000000,11500.000000,11500.000000,11500.000000,11500.000000,11500.000000,11500.000000,11500.000000,11500.000000,11500.000000
mean,-11.581391,-10.911565,-10.187130,-9.143043,-8.009739,-7.003478,-6.502087,-6.68713,-6.55800,-6.168435,...,-9.498870,-10.145739,-11.630348,-12.943478,-13.668870,-13.363304,-13.045043,-12.705130,-12.426000,-12.195652
std,165.626284,166.059609,163.524317,161.269041,160.998007,161.328725,161.467837,162.11912,162.03336,160.436352,...,165.235574,164.652883,166.149790,168.554058,168.556486,167.257290,164.241019,162.895832,162.886311,164.852015
min,-1839.000000,-1838.000000,-1835.000000,-1845.000000,-1791.000000,-1757.000000,-1832.000000,-1778.00000,-1840.00000,-1867.000000,...,-1860.000000,-1867.000000,-1865.000000,-1642.000000,-1723.000000,-1866.000000,-1863.000000,-1781.000000,-1727.000000,-1829.000000
25%,-54.000000,-55.000000,-54.000000,-54.000000,-54.000000,-54.000000,-54.000000,-55.00000,-55.00000,-54.000000,...,-55.000000,-55.000000,-56.000000,-56.000000,-56.000000,-55.000000,-56.000000,-55.000000,-55.000000,-55.000000
50%,-8.000000,-8.000000,-7.000000,-8.000000,-8.000000,-8.000000,-8.000000,-8.00000,-7.00000,-7.000000,...,-8.000000,-9.000000,-10.000000,-10.000000,-10.000000,-10.000000,-9.000000,-9.000000,-9.000000,-9.000000
75%,34.000000,35.000000,36.000000,36.000000,35.000000,36.000000,35.000000,36.00000,36.00000,35.250000,...,35.000000,34.000000,34.000000,33.000000,33.000000,34.000000,34.000000,34.000000,34.000000,34.000000
max,1726.000000,1713.000000,1697.000000,1612.000000,1518.000000,1816.000000,2047.000000,2047.00000,2047.00000,2047.000000,...,2047.000000,1777.000000,1472.000000,1319.000000,1436.000000,1733.000000,1958.000000,2047.000000,2047.000000,1915.000000

In [9]:
df['LABEL_TARGET'] = df['LABEL_TARGET'].astype(int)

## Verificando a porcentagem da distribuição da variavel alvo

In [11]:
# Comvertendo a coluna Target para int
def prevalencia(y_actual):
    return sum(y_actual) / len(y_actual)


print(f"Porcentagem da classe positiva no df: {prevalencia(df['LABEL_TARGET'].values)} %" )

Porcentagem da classe positiva no df: 0.2 %

*Como a porcentagem de aceites no DataFrame é relativamente pequena, utilizaremos a amostragem aleatória para selecionar uma amostra representativa. O objetivo é preservar as características originais do conjunto de dados, mas organizá-lo em três subconjuntos distintos: treino, teste e validação.*

### Verificando as colunas do Dataset

In [14]:
lista_colunas = df.columns.to_list()
colunas_entrada = lista_colunas[0:178] 
print(colunas_entrada)

['X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'X8', 'X9', 'X10', 'X11', 'X12', 'X13', 'X14', 'X15', 'X16', 'X17', 'X18', 'X19', 'X20', 'X21', 'X22', 'X23', 'X24', 'X25', 'X26', 'X27', 'X28', 'X29', 'X30', 'X31', 'X32', 'X33', 'X34', 'X35', 'X36', 'X37', 'X38', 'X39', 'X40', 'X41', 'X42', 'X43', 'X44', 'X45', 'X46', 'X47', 'X48', 'X49', 'X50', 'X51', 'X52', 'X53', 'X54', 'X55', 'X56', 'X57', 'X58', 'X59', 'X60', 'X61', 'X62', 'X63', 'X64', 'X65', 'X66', 'X67', 'X68', 'X69', 'X70', 'X71', 'X72', 'X73', 'X74', 'X75', 'X76', 'X77', 'X78', 'X79', 'X80', 'X81', 'X82', 'X83', 'X84', 'X85', 'X86', 'X87', 'X88', 'X89', 'X90', 'X91', 'X92', 'X93', 'X94', 'X95', 'X96', 'X97', 'X98', 'X99', 'X100', 'X101', 'X102', 'X103', 'X104', 'X105', 'X106', 'X107', 'X108', 'X109', 'X110', 'X111', 'X112', 'X113', 'X114', 'X115', 'X116', 'X117', 'X118', 'X119', 'X120', 'X121', 'X122', 'X123', 'X124', 'X125', 'X126', 'X127', 'X128', 'X129', 'X130', 'X131', 'X132', 'X133', 'X134', 'X135', 'X136', 'X137', 'X138', 'X139', 'X140', 'X141', 'X142', 'X143', 'X144', 'X145', 'X146', 'X147', 'X148', 'X149', 'X150', 'X151', 'X152', 'X153', 'X154', 'X155', 'X156', 'X157', 'X158', 'X159', 'X160', 'X161', 'X162', 'X163', 'X164', 'X165', 'X166', 'X167', 'X168', 'X169', 'X170', 'X171', 'X172', 'X173', 'X174', 'X175', 'X176', 'X177', 'X178']

In [15]:
duplicadas = df.columns[df.columns.duplicated()]
print(duplicadas)

Index([], dtype='object')

### Divisão do Dataset e Amostragem

In [17]:
df_data = df.sample(n = len(df))
df_data = df_data.reset_index(drop=True)

In [18]:
# Dvisão do Dataset em Treino , validação e teste

amostra_30 = df_data.sample(frac=0.3)

df_valid = amostra_30.sample(frac=0.5)

df_test = amostra_30.drop(df_valid.index)

df_treino = df_data.drop(amostra_30.index)

In [19]:
# Verificando Distribuição das amostras

# Aplicando nos conjuntos
print(f"Treino: {prevalencia(df_treino['LABEL_TARGET'].values) * 100:.2f}%")
print(f"Validação: {prevalencia(df_valid['LABEL_TARGET'].values) * 100:.2f}%")
print(f"Teste: {prevalencia(df_test['LABEL_TARGET'].values) * 100:.2f}%")

Treino: 20.15%
Validação: 19.19%
Teste: 20.12%

# Balanceameto de Classe

In [21]:
df_treino.shape

(8050, 179)

In [22]:
df_valid.shape

(1725, 179)

In [23]:
df_test.shape

(1725, 179)

In [24]:
df_test['LABEL_TARGET'].value_counts()

LABEL_TARGET
0    1378
1     347
Name: count, dtype: int64

In [25]:
def undersample(df, target_col="LABEL_TARGET", random_state=42):
    # separa classes
    classe_majoritaria = df[df[target_col] == 0]
    classe_minoritaria = df[df[target_col] == 1]

    # pega o tamanho da classe minoritária
    n_minoritaria = len(classe_minoritaria)

    # reduz a classe majoritária para o mesmo tamanho
    classe_majoritaria_reduzida = classe_majoritaria.sample(
        n=n_minoritaria, random_state=random_state
    )

    # junta novamente
    df_balanceado = pd.concat([classe_majoritaria_reduzida, classe_minoritaria])

    # embaralha
    df_balanceado = df_balanceado.sample(frac=1, random_state=random_state).reset_index(drop=True)

    return df_balanceado

# aplicando no conjunto
df_treino_bal = undersample(df_treino, "LABEL_TARGET")


# conferindo distribuição
print("Treino balanceado:\n", df_treino_bal['LABEL_TARGET'].value_counts())

Treino balanceado:
 LABEL_TARGET
1    1622
0    1622
Name: count, dtype: int64

# Verificando a Distribuição do Conjunto  e Salvando o Pré-Processamento

In [63]:
# Verificando Distribuição das amostras
print(f"Balanceamento em Treino: {prevalencia(df_treino_bal['LABEL_TARGET'].values) * 100:.2f}%")

Balanceamento em Treino: 50.00%

In [67]:
# Salavando os dados

df_treino.to_csv('dados/dados_treino.csv',index=False)
df_test.to_csv('dados/dados_teste.csv',index=False)
df_treino_bal.to_csv('dados/dados_treino_final.csv',index=False)
df_valid.to_csv('dados/dados_valid.csv',index=False)

In [71]:
# Salvando colunas

pickle.dump(colunas_entrada, open('dados/colunas_entrada.sav', 'wb'))